### PR TITLE
Implement `start_pos` per query for batch interface (reopen)

### PR DESCRIPTION
**Pull request by ufownl**
Reopen due to the unknown issue in #344 .

### CODE REVIEW

**Review by jan-wassenberg — APPROVED** [review]
Thank you :)

**Comment by ufownl** [comment]
What a strange issue. 😂

**Comment by jan-wassenberg** [comment]
:) hm, Github is still showing "This branch is out-of-date with the base branch" on this page. I can try to rebase your branch using the web UI.

**Comment by jan-wassenberg** [comment]
Weird, still happening. The import detected this pull request as still being part of the previous change.

I will manually patch the imported code :)

**Comment by jan-wassenberg** [comment]
We managed to land it. Sorry about the tool hiccup :)

**Pull request merged**
