### PR TITLE
Add overloads of `Image::ReadPPM` method

### PR DESCRIPTION
**Pull request by ufownl**
Make it able to load image data from a `hwy::Span`.

### CODE REVIEW

**Review by jan-wassenberg — DISMISSED** [review]
I'm curious what your use case for streams is?

**Comment by ufownl** [comment]
> I'm curious what your use case for streams is?

For example, receive image data from the network and cache it in RAM, then load and parse it from RAM directly. :)

**Comment by jan-wassenberg** [comment]
Got it, thanks. I'm not very familiar with network stacks, but haven't heard of std::istream being used in that context. Should we maybe move towards an in-memory interface where we pass in a hwy::Span<uint8_t> for the image bytes?

**Comment by ufownl** [comment]
I added a new overload to make it able to load image bytes from a`hwy::Span`. This is achieved with a custom stream class.

**Comment by jan-wassenberg** [comment]
Thanks for adding the Span overload. Wow, I haven't seen a custom stream buffer class before.
It seems like a fair amount of complexity. Wouldn't it be easier if the Span function was the main implementation, which reads uint8_t directly from the span, and if other callers have an istream of some kind, we can read bytes from stream into a vector and then pass that to the Span overload?

For our use case, this would also include reading from file. Note that io.h has a ReadFileToString helper function we could also use for that.

**Comment by ufownl** [comment]
The first solution I considered was the one you mentioned. However, P6 format files consist of a text header and binary data. If the Span overload was the main implementation, we must implement the text parser ourselves to parse the string and integers in the text header. It seems more complex than reusing `std::istream` in the standard library.

**Comment by jan-wassenberg** [comment]
Ah, I understand. One alternative we could consider is reusing some of the existing code from [JPEG XL](https://sourcegraph.com/github.com/libjxl/libjxl/-/blob/lib/extras/dec/pnm.cc?L265-267), in particular SkipWhitespace and ParseUnsigned. What do you think?

**Comment by ufownl** [comment]
Yeah, if we want to support more image formats in the future, using a parsing library like this is a better choice.

**Comment by ufownl** [comment]
I removed the `std::istream` overload and refactored the span version. Now, it directly parses the PPM format on the span.

**Review by jan-wassenberg — DISMISSED** [review]
Wonderful, thank you for making this change :D

**Comment by ufownl** [comment]
Sorry, I'm unfamiliar with Bazel, and it has been fixed. :)

**Review by jan-wassenberg — APPROVED** [review]
Thanks for making the change!

**Pull request merged**
