### PR TITLE
Additional cleanup after libgemma refactor https://github.com/google/gemma.cpp/pull/82

### PR DESCRIPTION
**Pull request by austinvhuang**
Will retarget this PR to `dev` once the `examples` branch PR merges to `dev`. https://github.com/google/gemma.cpp/pull/82 already was already large enough, these changes are left as a follow-up for now.

- Move command line argument definitions out of the gemma.h interface (to app.h)
- Fix off-by-1 printing of "." for prefill tokens
- Update libgemma commit hash for hello_world

### CODE REVIEW

**Comment by Zeenat30** [comment]
You are using my code without my consent

**Comment by Zeenat30** [comment]
My license with google I have lost it due to your theft

**Comment by austinvhuang** [comment]
Please be specific if you're raising an issue with the PR code.

**Comment by Zeenat30** [comment]
Screenshot_20240314_215353_Chrome

**Comment by Zeenat30** [comment]
Now this is facts theft is theft ask permission at least I was working on another project with my api

**Comment by jan-wassenberg** [comment]
I see a screenshot that appears to have nothing to do with this Gemma.cpp repository. Further such comments will be reported and deleted.

**Comment by Zeenat30** [comment]
I HAVE MANY MORE THE NAME WAS NOT GEMMA APP IT WAS GEMINI EVERYONE PU;;ED IT SO FAST IT WAS SHOCKING THET TOLD ME THEE USING IT FOR EDUCARTIONAL USAGE ITS MY API I PAY NOT U IF ANYTHIMG TRANSPIRES AS ITS FROM GOOGLE WHERE SHE USED BOTS AND SSH TO PULL IT OUT OF MT MASTER IF U LOO U WILL SEE ANOTHER SPAKING ABOUT IT BEING PULLED FROM MY MASTER FILE

**Comment by Zeenat30** [comment]
these are my google projects i am new i sent the screen shots to whom i am suppose to on github the screen shots where also deleted herewith she or he hacked my google console i will re send

**Comment by Zeenat30** [comment]
These are use as training models for my company so it does have something to do with gemma.cpp and now gemma2

**Comment by Zeenat30** [comment]
You can report it I have premium Microsoft endorsed GitHub thanks

**Pull request merged**
