### PR TITLE
Refactor `gemma/common.cc` to improve readability and safety

### PR DESCRIPTION
**Pull request by ericcurtin**
Use `std::size` for array size calculations. Replace C-style string manipulations with `std::string` methods. Simplify `std::transform` usage for case conversion.

### CODE REVIEW

**Review by jan-wassenberg — DISMISSED** [review]
Nice, thanks for making the change :)

**Comment by jan-wassenberg** [comment]
Apologies, I didn't see this PR is targeting main branch. Our import infra does not support that. Please change to dev branch :)

**Comment by ericcurtin** [comment]
Thanks, it's against dev now

**Comment by jan-wassenberg** [comment]
Thanks for rebasing :) I think the email address used is not covered by CLA?

**Comment by ericcurtin** [comment]
Author: @a-googler <no****ly​@google.com>

apparent didnt sign the CLA, dunno what that means :)

**Comment by jan-wassenberg** [comment]
Oh, I see. No idea how that a-googler got into the check. It might help to close this PR and open a new one? Sorry about the incidental complexity :(

**Comment by ericcurtin** [comment]
No problem 😄

**Comment by ericcurtin** [comment]
New PR:

https://github.com/google/gemma.cpp/pull/460

**Pull request closed without merging**
